#!/usr/bin/env bash
# This script transfers a file from our client to a server
# Requirements:
# Accepts 4 parameters
# 1. The path to the file to be transferred
# 2. The IP of the server we want to transfer the file to
# 3. The username scp connects with
# 4. The path to the SSH private key that scp uses

if [ $# -lt 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 0
fi

target=$1
host=$2
username=$3
private_key=$4

# copy file securely
scp -o 'StrictHostKeyChecking accept-new'  -i "$private_key" "$target" "$username"@"$host":~/
