#!/usr/bin/env bash
# Install nginx web server
# Requirements
# Install nginx on your web-01
# server
# * Nginx should be listening on port 80
# * When querying Nginx at its root / with a GET request (requesting a page) using curl, it must #   return a page that contains the string Hello World!
# * As an answer file, write a Bash script that configures a new Ubuntu machine to respect above #   requirements (this script will be run on the server itself)
# * You can’t use systemctl for restarting nginx
# update packages local DB &&  install nginx package && allow port 80 && start nginx && set www directory owner && set default response file
sudo apt update && sudo apt install nginx -y && sudo ufw allow 'Nginx HTTP' && sudo service nginx start && sudo chown -R "$USER":"$USER" /var/www && echo 'Hello World!' > /var/www/html/index.html
