#!/usr/bin/env bash
# Double the number of webservers
# update packages local DB
sudo apt update
# install nginx package
sudo apt install nginx -y
# allow port 80
sudo ufw allow 'Nginx HTTP'
# start nginx
sudo service nginx start
# set www directory owner
sudo chown -R "$USER":"$USER" /var/www
# set default response file
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ \tserver_name _;\n\tadd_header X-Served-By \$hostname;\n" /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
