#!/usr/bin/env bash
# manages manage_my_process
if [ "$1" = "start" ]
then
	bash ./manage_my_process &
	echo $$ > "/var/run/my_process.pid"
	echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
	sudo pkill -f manage_my_process &
	rm "/var/run/my_process.pid"
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
	sudo pkill -f manage_my_process &
	sleep 2 &
	rm "/var/run/my_process.pid"
	echo $$ > "/var/run/my_process.pid"
	bash ./manage_my_process &
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
