#!/usr/bin/env bash
# Displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is
#+ displayed (refer to the example)
LIST="$(ls -1)"

for filename in $LIST;do
	echo "$filename" | cut -d "-" -f 2
done;
