#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code from the Apache log file.
filename="apache-access.log"

awk -v FPAT='([^ ]*)|("[^"]*")' '{print $8,$1,$7}' $filename | sort -nur
