#!/usr/bin/env bash
# gives you information about the school file.
filename="school"

# check if file exists
if [ -e $filename ]
then
	echo "$filename file exists"

	# check if file is empty
	if [ -s $filename ]
	then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi

	# check if is a regular file
	if [ -f $filename ]
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
